//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiV5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treniruotes
    {
        public int Id { get; set; }
        public Nullable<int> UsersId { get; set; }
        public System.DateTime Time { get; set; }
        public int FreeSpaces { get; set; }
        public int Joins { get; set; }
        public string TName { get; set; }
    }
}
